FROM ubuntu:22.04

RUN apt update && \
    apt install --yes software-properties-common && \
    apt-add-repository --yes --update ppa:ansible/ansible && \
    apt install --yes ansible

RUN echo '[local]\nlocalhost\n' > /etc/ansible/hosts
